{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "On The Way Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "on_the_way_deliveries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pending_deliveries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_deliveries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Delivery Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "average_delivery_time_sum / average_delivery_time_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}